[project]
name = "context-param"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=4.4.1",
    "numpy>=2.3.5",
    "pandas>=2.3.3",
    "torch>=2.9.1",
]
